import "./globals.css";
import { Inter, Titillium_Web } from "next/font/google";
import Navbar from "@/app/components/Navbar";

const TitilliumWeb = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900"],
});

export const metadata = {
  title: "Youtube Watch Time",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={TitilliumWeb.className}>
        <div className="container mb-2 mt-2">
          <Navbar />
        </div>
        <div className="container mt-2 mb-2">{children}</div>
      </body>
    </html>
  );
}
